services:
  rayobrowse:
    image: rayobyte/rayobrowse:latest
    restart: unless-stopped
    shm_size: '2g'
    security_opt:
      - seccomp=unconfined
    network_mode: host
    volumes:
      - rayobrowse-data:/data
    environment:
      - STEALTH_BROWSER_NOVNC=true

volumes:
  rayobrowse-data:
